# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bb8ff35a-0c55-4cad-bd43-bc73bbbd31f6";
    fsType = "btrfs";
    options = [ "subvol=@nixos" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/bb8ff35a-0c55-4cad-bd43-bc73bbbd31f6";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CDFD-98B7";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/ssdata" = {
    device = "/dev/disk/by-uuid/310543a9-ab22-4740-a4e9-0cc158fa93f6";
    fsType = "btrfs";
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/1c810006-c89b-44c0-8f43-5be94de8d487";
    fsType = "btrfs";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/4c3de8ee-c1b6-4ef0-b378-acc60c02dbbd"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
